apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-sealed
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBilW0n5TIkDS9swH6gJJTwAgXPoypb5e8trw+HNeUIhuVCCg70142QDumLYcQL0xZJ+ltQaRI3bTYcajNb6QN3WFuybiyrwHhEERubdLJChpYOMNfXHrSnnpWbl/qrG78M4SMOeSbjwC6XYxChRlmijbyylyZ1hyVAXCTmlIq5BzaMd3GTncJNTMGPDzR+69F9wnfZydA2fiJrG7LixyUT4771JMzLXF/t7fbSnzb6+2i7uRNVv0qOc5QHYcjpUUIERMtW13uLRG1ovs/BzcQWwD/MF84YyI2xHfFz2eordBOHvxkHe/QNb93d+HSDLLRCM0f16rSiV+vDRppg3reHb17SoRqWuyb9wCVSdDisEdjQABBpRSD+FuSXXVJ4LM1x7VsY8AzgZHCgFnt7IVksj9pVvFaBspqRAtnh6z0ytMmg3pBIxzLDOhTba+vTCz9ONDUymVg1pgZzs4Jx6PvROjrAf6vYTbCSnkJw4okbf2VxzfoifIn0qnp6eRXEMKKRG9I2cmA335cXZEtOs6PQCSfJs2r2jUVQKWfAqF8BjwkhmaKuc3/VMeM+ngWEy0IEdye2reKBP3hHklPj9A6wejZXxBsP5XpeYHWPH2Jzq0MwiUQoz5Qg42Ky4rcFj4+MHxuH7QnzXSM2vyul3mSETrWGzR1mPgvgo4m+/+iNobHm/fE8VeLzMZeTjaFaAHrM4SKCC63isw==
    admin-user: AgCWmPIVwwfRpeFMTBbXcfmmROmmnp+goYqAmjK7wyhO2Ab10P3Xzo6MBwiXehcTX4Jbg8zFmi6sjWdaHlXUBfsJezt1xFpPbAIsJUty8vc+4Otcd8g0yy4bsJxjTO5TvONqzlf5cUCqb8gy0Td0BwzDfmI1F/FGdWNINr52U4vXo8MYUCojeL4+26k6mABTd02P9EDq7KhPqNww+leBskooRGcyGHlYXU3o2PjRE2BQGd9w7P/ZedtzMo5VLqc4hIPVgspivilxbpVzWYvZO+CtJ7HeVIW+k5z0KY7wWldI+H4gM0PwSvP1z10t+BfmGZ9V2NHv99clw2+dRd2VJZ+IUJtOHoX9+dwAwcHUXsSq//WjwUD1njZZ8uKaIH9p7EqxvZstYGX5ep/g9ckpKWXmk9Ns78v0DXC73TQVPHF0TcebLqg4e3abJH6kikacDHyzkxczpwhMHJRVCrE4ohRSR+kFX2uEKcilMKIRFxvvFQ4ZCXIgg2tnzywlbRqogKLB3r5WxfxYbEXpoDjKgB15eKwv9wFCwgWyEuT8hBgoecnyLzTrC9wGxCeH8nMK4i/GYLtUlahVMZbp7S6AEjCpdYmdkGT/WYJL1FQwRtAVYzqlWff8cYQj5kpctHnrc3ZYqesXlmwecNTN7gCEakpC4m+TRjJlEdjREYAb2WvdJwzq2bFmYA2/Re8kqRqhc5yXXpbiWw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
