apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBF9/WRFt17rdv9KBcIqjCWuC71oHh7IdSKTFOKMK5aja/OVii7uu4lZmYFIus9OsYUyVkMb86rT8QluwoCek9Qx06fWXKsDhft9ISTbq4jqNtD+2AGP/EdPoW0zU8b+C6kGOTp4eZ4qURVdcxfupmFn0rhEteqFP7FHVaVqhb7hUKNJN47o9Kb32yY3egozsPELWDk66g0NrG/v6zyohD6dzlSS8CmQPBdVw/RcciDIsgwzFmTtSyMOc+X4/pXOrrW5uhjyQERHYB1qXHFhmv1toNWd6tZa4gKv66WjcFgjMW2sKC9W5yj6QTMrU3WWh/dgL0oGK6k5dkia+0r+CYHQOwDAuENYPFms31BCK8IT18NnXBwHP3vC8cmsYn/kjAq9ylUwi8itucmM/c0GJ8yKyFEuOuVYYZSWCHk4EBtePOT6zK6mifVuFblnPkcMhIUX2hIqeDQq8xXZ4vD3ClaVJP9h0FNK7USe8LZSpP0HSpQpfPrkj4TYAyfgjrX5b2CFnTBzp+0XTvTCMu8gdPsrX7hUeX7NZJGOdg2m0taAmntl5Wo73KlMGUpeVCzB2yF3vRDGreG7BnbTIVc9WijozvS2lLzN6vVB6lyFYXc83fzJwQz/nJBGF1kpi2pjKW8QHN95AX4tsky27Gt8xmnN0Yqb1eCpsQwy7iyc7G7gRqHD0yS8YqHLfx2Tz8byXs4k3yu
    admin-user: AgCLvc+UuRvMW41pwZ6Jcy+BZmZoS60/yGN6Z5ryPojCdUFvSndxZhnxYw8UQKRbkeowyHFVSHDbGep8GWq0yTx+AwPy2j8I74EB8MK+2Tp3J8zMgvvnJK4/kVtWIhu4ybJl4zbU6vRF70iyphoIA0GpyhcThELmHCJuTM7SrYjisQPjioKZpEAl7wz41+2tscv9bNcBrh7nCu6e/dhSZ/6hyr4InHHtA9iy6h71ZZKVTql6N9Ll4dtLLw6SaFcznXVKTWK1Ux1Bc6EMiinl0U+j2JeMv9+jqdkgZ8Oq2nBsUBtydLeUTCkQJMFt/t2q5oPJIU/UhbeN1fm7f4ooDfG561ArY7EFiS7MOIBk17pyoV3Lr1rZNw3aDg35idm8jkFnSvVKcybbOhtaEyEmdhWhB62VfucUnkisWHK3msBrtD7rRLSQThl6k0SaeL7eMecJ3l17xSLFvblItdwDRLQxuFo4hDFLK3i8wSooLMcwp6khgLvBi6ll2EsXBbdf77kcODsDApJonUCENvpXE5sqgTS1ROTRDL94fNe6ZSMu62mlnDEaG2thZOeikifh7/dPHcoXkjrWJor9mbPdiQ87OgRV6Wd9oXevNHytVHDVhGW9TLnsq3QK+kKjwaYRbuCY/oyBAyeZuGirbIc/jiunl1qJHmXOhKKIjLnSeq2rXXyIqsLOjy/i5QfIs1/IC/Z5I1iL
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability

