apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCiIUp60oi1QOPzmLI6D4GlZCRT6h0kOJ25/PJNMhWfNKLgY1zxIfDZMVH7yR3RQQyeZiLEWpF29QgpJzWbhRbngHjg5NsiIWljSgip9Z173EAPRtLz0vPA2Bix7hZVVnDYRBQC/TATHrR9xZCcpUX9+vvZMdVeFQxk29pBBwN8Df6r36QUbzCwc2jND1VKbmfDAAYYRYWVmriKGEOtF2TyZCJF/A0mPPXNJWmy5/M6Zgc4nQr9ScyUk9nKXLO+ApMJXISmF2AsCM30E63TBCygxrb8jQA5+jj/IVedKeRddSSyw6Mi8+BXrciibfJRHUNQu/aWHyNhJcP8KVhSFl287+MT/KkniuK3qvWLK/IRaC/Yl8JXS6VZwNWiytGIf/ydljxqV6mbSymAaL7k9bawDA1U1ChUKTYB93DkvX2PaEgMNXhaqRzo9sJ70rpPN76bIWIM/djONxKpWxkghB8GxurYGikxl4Hy906c9yi2k3aaxfEjWrtIFOPgsa9fzxqQwVAUixmRswDsKDHnqG0zRYrXAvV+Zca4IyKF/w6W4zutwOYD3C5S79Ah+Tp9YkE65KaC0hu0ax5pm4ZFt+TN2HieFOxXYtTWFaTQOMK6aD/FwEo6xLimzGFc5lKDFUmH9K+Sq3f0z+1aXn5S4Dcw/rn9U+0Vs4a88KTktw6uBfQuwExdGGI+hkOHHARS5z/RFuKx
    admin-user: AgBZaTv3OH3i1131E5PQ3HTIAKfFxuNX42Ii1LHXwB+6j2aY0XH/nx4LlCanmKUrqQxY+54CACE2Z3YZSxm/q7UiWotC5Oa8Tt0aGc2kzXME58qBiPIzRDfo6sUWsrUL0khXoZWHjcEtBQMktmDBsymyT6cyBBcUjPiz2BfYJlPYFROWplyt/QVuZ0uga2z2wt+2OihTZnrdfXQvnGKR75KNEn+w9THwS6CZWnFZKX/BBKmLlqJJOwj1mEbRAaXPY0MzT6o/aomItbv5IkCjASAHQmjv7ji0O3LJQc4PJ/PPFRGUOFTYFkwC78QsQYXoApR9PnS+P/5fjxzoHUvNDp+L+e+Zgz1WT1Dm91q9oobqYc5Dh2ubDqMenlXfR0ypsRG4++fuhJ2RIKY8g8nlUx/mtDmwehMRVXFkJ8G96AZv7Lsk8XwMoRwqzvlt3C8loxpPMg1EAqYW/xEmIbmyyVVD+MxgWqiEL0s7V0yGoQvmNC51lc39chbI8iwN1kuL2aA+qXE8MK1uKIILQr7WYi8fNWs7r5vYmrPtCXzwW/U277XQXGB+NzX/VxWCmvSJzrqOsSG/8jdrW4ksMiRhhExV8wH3h5Gj4EPRLPPcH4KL9rXd1MTuGfvOfesIhvoTg9m3QjPn2eQveNO8shyjiBrXNh+9iaz92PmccnXIftXeBFgIvH8Fs2mIwrjP5gUnF6wpur99Lw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability

