apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-auto-setup
  namespace: observability
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      containers:
      - name: kibana-setup
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            until $(curl -s -o /dev/null -w "%{http_code}" http://kibana:5601/api/status | grep -q "200"); do
              sleep 5;
            done;
            # Importa o Index Pattern via arquivo JSON
            curl -X POST "http://kibana:5601/api/saved_objects/index-pattern/app-logs-pattern" \
            -H "kbn-xsrf: true" -H "Content-Type: application/json" \
            -d @/data/index-pattern.json
            curl -X POST "http://kibana:5601/api/alerting/rule" \
            -H "kbn-xsrf: true" -H "Content-Type: application/json" \
            -d @/data/alert-rule.json
        volumeMounts:
        - name: setup-data
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: setup-data
        configMap:
          name: kibana-setup-config