apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-admin
  namespace: observability
spec:
  encryptedData:
    password: AgCMTWtchj9Nf32nqRMlxmjAm7FESmQjMiCZtmFWUX3TeWWFsji0DQMwT0CZt9ldGvUOVvEU6v/QVyWi0RH6w6BTgz4wtYZsl0/dtPl4gEp1E6tklit+erD1kmbDLK25m35KEkvxkf4Hw3driWRE3zpmp2EThlIj4qTZIPopCO8bi33XQgPcMYTszqlyuj8PSJodrAhUz3rLzDrpt24Gyyhl+02Rhmpdp4+fE1SNzy5L6KfBkWHfOFq8UImYXo3kqRCoJILVdwlan1MqAPYS+MWuaG0BPmPUKRz/IaNtBH7cGlmcrbri3iO+0Hol/pqcxe3MKpMJ2MZp1Bg3Rj7oXLVNVsJEpspp15evDr/+4Z+8aeB+8MuAsTh/8TKmBWdJ5NNssGSuWoVsb7ZdJunbrRj7PnMBVGgzRuaAhwirZYykAF1ucgQMI2gcAVGOX0hsjNGBBmolI0YGSM7QvXU8uEag8VXawgvu2MP5hIP299qMENGs9UhAywdceLgA+fJDg8UBu0ML5uvT699mlda+pnQrBtZ8Q7zwe0AwrPYBE2MeOvt0JuMuL3E0uVV4wAK2M9us6H5L43a9FnDzKhzGaMGTgpCkVUhmMMnxtQjiSbue7WvXETpUNWO90QwPQQK6n4RCXa5bnQE6gmHCRhufNliC7Ay6slb0gPIGSXiNHpGxpfwSp/hAZWhaiKtnUkb7975aOQlzfkiLog==
    username: AgBRERuIA92qfMZ39cLNXO1whk0uvev3ebfRMXSzXvP+aQId+RzGhJQyHx2juPNJM22acolB0vzVts07JBxmiCJ+Xp1VMHU58/juX6qAX4Yvg9ejothC/wvsQB4W7WadOhjRHhELn8DxfrCtyWIrFu2oIOz7Yu5sii0DTAQSYXSR+kaKx7puESuaFQcpLiTdMcOt9gyLkt41an7zHe4gAabLr+lORC0m1S8BBVCWEoJf6VEXovzDjQyO5Jz4e3L/9R9tINUGKUjxou606xfgOjlA/IVJ3tkkI41Htfa4PuDhVkFn91Nz+FOrRQ3+bQU1s7i6i9k+l1Mw83xKDLh2uzy4Wxm2J+cYq/vaqaevRhH3BdEdsDes1ZvAW6AIx6cMMfuIVZG/wxFvO8+fKRwy8iPFNczSVux9CDG0taCo5tZ5DKSbz/mJFh6w6D6cT6YohHvkJPHG9dzYaxEIEIKpKAQexgsR4ZTZHOESoG07hnZUCNdfr6YcQskzQpYhXhdYd5NpGsQl8DqNOrxOSbOITo/OzIxhHl/MHRZxLzqAgv8PndqQlB6KRu40kggOOfOZKiZOVK1lN2DsbZEQBg72HRfZqW5UHsf2J1L1/ljc7yYBe/EGYZCDEXGySHwSjsSHMd/lEjb+tSIxB6NjfTEY1gOzu3w9QfE3LOdoFMkHtUldHYgpsovFuVnQ1O8m9fK/6M4urKzbblGl
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-admin
      namespace: observability

